name = "NonlinearTestProblems"
uuid = "84d880b8-0062-4738-ba75-b6cb1662e554"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1"
ArgCheck = "1, 2"
DocStringExtensions = "0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
